### ISSUE TITLE
Feature Request: Release package signing

### ISSUE THREAD

**Issue by g4jc** [cracklib/cracklib#10]
Hello,
There is currently no way to verify the complete integrity of releases. Please consider signing your releases so that package maintainers can verify the sources prior to packaging.

See here for how-to and complete details:
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

Thank you

**Comment by Neustradamus** [comment]
@nneul: What do you think?

**Comment by nneul** [comment]
Will keep in mind for next release.

**Comment by g4jc** [comment]
Since this request was made, there are also helper scripts - such as [GPGGit](https://github.com/NicoHood/gpgit) to help automate the process. Thanks for looking into this! :+1:

**Comment by nneul** [comment]
Signed v2.10.0 with 350D0B0705E9C3CB / nneul@neulinger.org
