### ISSUE TITLE
The point in time when the master branch was migrated to the main branch.

### ISSUE THREAD

**Issue by sliang1314** [cracklib/cracklib#108]
Could you please tell me when the **master** was migrated to the **main branch**? It seems that there are no records of the branch change available to view. Thank you!

**Comment by wandering-tales** [comment]
> Yeah this broke my bake, but it was an easy fix :)

How did you solve? :)

**Comment by tbandtg** [comment]
well since tags and hashes still match


# File: cracklib_2.9.8.bbappend

# Update the branch to 'main'
SRC_URI = "git://github.com/cracklib/cracklib;protocol=https;branch=main \
           file://0001-packlib.c-support-dictionary-byte-order-dependent.patch \
           file://0002-craklib-fix-testnum-and-teststr-failed.patch \
           "

**Comment by vapier** [comment]
history was not changed -- things weren't rewritten between `master` & `main`, the branch was simply renamed.  just update any references to `master` to use `main`.

although not sure why distros are pulling from `HEAD` in the first place -- they should mostly stick to tagged releases instead.

**Comment by wandering-tales** [comment]
> well since tags and hashes still match
> 
> 
> # File: cracklib_2.9.8.bbappend
> 
> # Update the branch to 'main'
> SRC_URI = "git://github.com/cracklib/cracklib;protocol=https;branch=main \
>            file://0001-packlib.c-support-dictionary-byte-order-dependent.patch \
>            file://0002-craklib-fix-testnum-and-teststr-failed.patch \
>            "

Why the patches?

**Comment by tbandtg** [comment]
They were part of the bsp I was using.
