### ISSUE TITLE
cracklib-format only recognize .gz archives

### ISSUE THREAD

**Issue by fundawang** [cracklib/cracklib#113]
https://github.com/cracklib/cracklib/blob/main/src/util/cracklib-format

The script only recognize .gz archives, while we offer `cracklib-words` as multiple formats such as `.xz` and `.bz2`. Maybe it could be improved?

**Comment by nneul** [comment]
Added some basic support in latest main. Likely won't do a release specifically for this though, but it should get rolled into next time a release is done.
