### ISSUE TITLE
bad zh_CN translation file

### ISSUE THREAD

**Issue by gumblex** [cracklib/cracklib#12]
In https://github.com/cracklib/cracklib/blob/master/src/po/zh_CN.po, the translations are all question marks.

**Comment by vapier** [comment]
looks like it was corrupted a while ago:

```
commit d5e727a4a0aa744c57cb8bd2091c20eee409f8a8
Author: jandd <jandd@4175fe1e-86d5-4fdc-8e6a-506fab9d8533>
Date:   Wed Sep 22 07:58:23 2010 +0000

    updated Wei Liu (zh_CN) translation (Leah Liu)

    git-svn-id: svn://svn.code.sf.net/p/cracklib/code/trunk@174 4175fe1e-86d5-4fdc-8e6a-506fab9d8533
...
 #: lib/fascist.c:550
 msgid "you are not registered in the password file"
-msgstr "尚未在口令文件中注册"
+msgstr "??????????????????????????????"
```

the zanata website has updated translation:
https://fedora.zanata.org/iteration/view/cracklib/master/languages/zh-CN

so we need someone with the zanata cli installed to sync & send a PR.  the tool appears to only be available on Fedora systems and is written in Java.

**Comment by piotrdrag** [comment]
There you go: https://github.com/cracklib/cracklib/pull/22 :)
