### ISSUE TITLE
simple passwords test

### ISSUE THREAD

**Issue by NoName115** [cracklib/cracklib#16]
I tested the CrackLib library with RockYou password list and i found out that passwords which are not too short and contain a space character are in 90\% of cases accepted, the passwords are quite simple,
e.g. 'rock you', 'love you', 'harry potter'.

And passwords that have at least 2 digits as prefix and postfix and are longer than 7 characters are accepted in 70\% of cases,
e.g. '123hello123', '123love456', '26dogs26'.

**Comment by wwalker** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1806354

```
wayne walker: OK
wayne-walker: OK
```

**Comment by ceving** [comment]
I do not understand, why a password gets accepted, if a dictionary word gets appended by 123.

~~~
# LANG=C cracklib-check 
secret
secret: it is based on a dictionary word
secret123
secret123: OK
~~~

The "secret" in "secret123" is still based on a dictionary word.

**Comment by nneul** [comment]
secret123 is reported as failure - did you install an appropriate dictionary?

Above examples like '123hello123', '123love456' also show as rejected. That may be something with how you imported dictionary if you're still seeing the symptom. 

I don't see the symptom with that redhat bug report either - it correctly matches against my own:

```nneul@optic:/local/cracklib/cracklib/src (master)$ echo "nathan" | ./util/cracklib-check 
nathan: it does not contain enough DIFFERENT characters
nneul@optic:/local/cracklib/cracklib/src (master)$ echo "nathan neulinger" | ./util/cracklib-check 
nathan neulinger: it is derived from your password entry
nneul@optic:/local/cracklib/cracklib/src (master)$ echo "nathan-neulinger" | ./util/cracklib-check 
nathan-neulinger: it is derived from your password entry
nneul@optic:/local/cracklib/cracklib/src (master)$ echo "Nathan-neulinger" | ./util/cracklib-check 
Nathan-neulinger: it is derived from your password entry
```
