### ISSUE TITLE
distdifference incorrect

### ISSUE THREAD

**Issue by Coread** [cracklib/cracklib#17]
In the distdifference function it should be less than "<" rather than "<=". Looks like a translation error from the C code. The result is that different strings report a difference of 1 less than it should be e.g. 
```python
In [6]: cracklib.distance('xxxxxx', 'kkkkkk')
Out[6]: 5
In [11]: cracklib.distance('a', 'b')
Out[11]: 0
```

**Comment by Neustradamus** [comment]
@nneul, @jandd: Can be closed no?
