### ISSUE TITLE
Cracklib words missing from Releases

### ISSUE THREAD

**Issue by tiredofit** [cracklib/cracklib#21]
Sometime in the past week the cracklib-words-2.9.6.gz has disappeared from your repository. Would you able oto restore? Could be related to previous issue of rearranging the releases section.

**Comment by Neustradamus** [comment]
@tiredofit, @nneul knows, it is planned to have soon with the 2.9.6 tags etc...
Linked to https://github.com/cracklib/cracklib/issues/20

**Comment by Neustradamus** [comment]
There is the last build here: https://github.com/cracklib/cracklib/releases/tag/v2.9.7

**Comment by Neustradamus** [comment]
@nneul: Can be closed no?
