### ISSUE TITLE
error loading dictionary

### ISSUE THREAD

**Issue by alciono** [cracklib/cracklib#23]
Just after installing cracklib on two different computers I get the following result on each of them when trying to use it for the first time:

echo "123456" | cracklib-check 
/nix/store/nck25bk78fhrx70fs8v80hmr0k1z3b39-cracklib-2.9.6/share/cracklib/pw_dict.pwd.gz: No such file or directory
123456: error loading dictionary

**Comment by vapier** [comment]
make sure you've run `create-cracklib-dict` to compile the dictionary first.  you'll want to feed it a database as can be found in the words/ subdir of this repo.
