### ISSUE TITLE
The name of cracklib

### ISSUE THREAD

**Issue by pajuja** [cracklib/cracklib#27]
Hi, is the name of cracklib thought to be a good one?

**Comment by tomato42** [comment]
Why a name that uses an onomatopoeia for things (passwords) breaking would be a bad one?

**Comment by pajuja** [comment]
Well, it has quite bad connotation.

**Comment by tomato42** [comment]
like what? "crack of dawn"?

**Comment by pajuja** [comment]
Nevermind. :D
