### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [cracklib/cracklib#28]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by Neustradamus** [comment]
@nneul: Have you seen?

**Comment by nneul** [comment]
I have not been actively involved in any translation efforts, so not sure I'm in position to answer most of this.

**Comment by Jibec** [comment]
hello no worries, just tell what you know and where you need help,

to pull translations, you just have to run `zanata --pull` (zanata client is available in pip).
If you can't lock the project in Zanata, just tell me.

**Comment by nneul** [comment]
Yeah, I'm not aware of any credentials for zanata, never even heard of that tool before. I can say that master is the development branch, though it's currently pretty inactive.

**Comment by nneul** [comment]
You sure this project is even present on zanata?

**Comment by Jibec** [comment]
once the PR is merged, I'll configure weblate. And this will be done.

**Comment by nneul** [comment]
Merged, please add my FAS user (nneul) with rights to the project when you get it populated.

**Comment by Jibec** [comment]
migration is done: https://translate.fedoraproject.org/projects/cracklib/
nneul is admin

weblate will update each po files each time you update the pot files (don't do it manually)
weblate will squash commits per author until the PR is merged
