### ISSUE TITLE
Warning generated when create-cracklib-dict is run due to issue with the supplied word files

### ISSUE THREAD

**Issue by dermotbradley** [cracklib/cracklib#32]
Line number 31,566 of the provided word file myspace.txt.bz2 is 6341 characters in length. The cracklib-packer program however only reads up to 1022 characters of a line at a time, any line longer than this is actually treated as multiple separate lines which can then produce "input out of order" warnings if the resultant "new" lines do not happen to appear in sorted order.

Also if any of the input lines are blank, including after cracklib-format has performed some "tr" actions on them a "skipping line: <LINE NUMBER>" message is displayed. 

When running create-cracklib-dict against the supplied word files the result is the following output:

```
skipping line: 1
warning: input out of order: 'ghabcdefghabcdefghabcdefghabcd' should not follow 'habcdefghabcdefghabcdefghabcde' (line 55371)
warning: input out of order: 'fghabcdefghabcdefghabcdefghabc' should not follow 'ghabcdefghabcdefghabcdefghabcd' (line 55372)
warning: input out of order: 'efghabcdefghabcdefghabcdefghab' should not follow 'fghabcdefghabcdefghabcdefghabc' (line 55373)
warning: input out of order: 'fghabcdefghabcdefghabcdefghabc' should not follow 'ghabcdefghabcdefghabcdefghabcd' (line 55375)
warning: input out of order: 'abcdefghi' should not follow 'fghabcdefghabcdefghabcdefghabc' (line 55376)
```
This is the same issue previously reported in #15 3 years ago.

I will be raising a PR to modify the cracklib-format script, used by create-cracklib-dict, to remove these output messages.

A decision still needs to be made whether or not to clean up the myspace.txt.bz2 file to deal with the long line.

**Comment by Neustradamus** [comment]
@nneul: Can you look?

**Comment by nneul** [comment]
Waiting for PR to be submitted.

**Comment by nneul** [comment]
Actually, never mind, this was submitted, and was merged - just never got the issue closed.
