### ISSUE TITLE
A new version? 2.9.8?

### ISSUE THREAD

**Issue by Neustradamus** [cracklib/cracklib#35]
@nneul: The last version is 2.9.7: @nneul released this Mar 3, 2019.

Two years in few days.

Can you release a 2.9.8?

Thanks in advance.

**Comment by nneul** [comment]
will try to get to this soon... just have to find the time.

**Comment by kloczek** [comment]
Before release it would be good to merge some fedora patches and probably ,man pages from debian as well.
If you want I can try to make PR.

**Comment by nneul** [comment]
That would be great!

**Comment by kloczek** [comment]
List of patches which IMO it would be good to commit before release
https://src.fedoraproject.org/rpms/cracklib/raw/rawhide/f/cracklib-2.9.1-inttypes.patch
https://src.fedoraproject.org/rpms/cracklib/raw/rawhide/f/cracklib-2.9.0-python-gzdicts.patch
https://src.fedoraproject.org/rpms/cracklib/raw/rawhide/f/cracklib-2.9.6-coverity.patch
https://src.fedoraproject.org/rpms/cracklib/raw/rawhide/f/cracklib-2.9.6-lookup.patch
And from debian http://ftp.us.debian.org/debian/pool/main/c/cracklib2/cracklib2_2.9.6-3.4.debian.tar.xz would be good to merge some man pages update-cracklib.8 cracklib-format.8 cracklib-check.8 FascistCheck.3 and update-cracklib script

**Comment by vapier** [comment]
would be good if they sent PRs for them

**Comment by Neustradamus** [comment]
Of course, it is really better to create PRs for all patches from OS (in all projects like here) ;)

**Comment by kloczek** [comment]
OK I've created https://github.com/cracklib/cracklib/pull/37
Please review and double check :)

**Comment by kloczek** [comment]
I've added yet another two commits and tested agaoin with dowloaded whole patch https://github.com/cracklib/cracklib/pull/37 with my rpm package and for now that is all :)

**Comment by cheng362432** [comment]
Are there any plans to release a new version？

**Comment by kloczek** [comment]
Gentle ping .. 😋

**Comment by nneul** [comment]
Published v2.9.8. Sorry for the long delay!

**Comment by kloczek** [comment]
Thank you very much 👍 😄
