### ISSUE TITLE
Inconsistent license claims in Python bindings

### ISSUE THREAD

**Issue by rbu** [cracklib/cracklib#5]
It is not clear whether Python bindings are under LGPL or GPL:

I find references to the LGPL in src/python/_cracklib.c and src/python/cracklib.py, as well as the "classifiers=" in src/python/setup.py.
However, src/python/setup.py's comment header as well as the "license=" parameter state a GPL license.

@jandd, can you please confirm the intended license?

**Comment by jandd** [comment]
The intended license is LGPL as for the rest of cracklib. I'll change the setup.py.
