### ISSUE TITLE
naming of /usr/sbin/packer conflicts with hashicorp packer utility

### ISSUE THREAD

**Issue by jeremyeder** [cracklib/cracklib#7]
Hi all --

I'm following up on a request to include Hashicorp's [packer](https://www.packer.io/) tool in Fedora, and I notice there is a naming collision on the packer binary that's been [tripping up some users](https://github.com/mitchellh/packer/issues/1117) for a few years.

The story is that cracklibs distributes a binary file called `/usr/sbin/packer` on Fedora and RHEL, and  Packer from hashicorp is right now a single statically linked go binary called `packer`.

In hopes that we can include Hashicorp's packer in Fedora I am wondering how we can resolve this collision.  For example, would it be possible to rename `/usr/sbin/packer` to `/usr/sbin/packer-cracklibs` ?

**Comment by GeorgeSapkin** [comment]
`/usr/sbin/packer` already points to `/usr/sbin/cracklib-packer` so there's no need in renaming. Maybe removing the symlink is an option?

**Comment by jandd** [comment]
Just as a data point: the Debian cracklib-runtime package does contain /usr/sbin/cracklib-packer so there is prior art that cracklib does not depend on a binary named packer (see https://packages.debian.org/jessie/amd64/cracklib-runtime/filelist)

**Comment by jgallucci32** [comment]
Just came across this issue; pretty annoying. Upgraded from RHEL6 to RHEL7 and now my packer builds are failing due to /usr/local/sbin being in the PATH before /usr/local/bin where I keep the packer (Hashicorp) binary.

I recommend the symlink be removed permantently as well. It did not exist in RHEL6 no reason to create a conflicting binary in RHEL7.

**Comment by tomato42** [comment]
Please contact Red Hat customer support directly about issues in RHEL packages.

**Comment by wayneworkman** [comment]
I too have this issue, both on RHEL 7 and CentOS 7. Removing the symbolic link doesn't seem to work.

**Comment by fernandotower** [comment]
I solve the problem in fedora26 changing the file name to cracklib-packer
su
mv /usr/sbin/cracklib-packer /usr/sbin/cracklib-packer_old

**Comment by et304383** [comment]
I just encountered this.  I love how I googled only `cracklib-packer` and this is the first link that came up.

Clearly, this symlink isn't useful when the number one Google result is "this conflicts with the real packer"

**Comment by smakintel** [comment]
just `unlink /usr/sbin/packer` will do the trick

**Comment by antoinetran** [comment]
packer cracklit is an essential utility of CentOs/RedHat, we cannot even remove it with `yum remove cracklib-dicts` because this is used by systemd. Who can be sure that no utility in CentOs/Redhat (or Fedora) does not refers to packer as packer? Even if this is mostly a Redhat issue, I wrote this as a warning againt unlinking it. I will refers to packer with an alias in my script. As an alternative, one can use yacker ^^

**Comment by aaronk1** [comment]
> just `unlink /usr/sbin/packer` will do the trick

Has anyone seen this break something?  I like the idea of this solution but I wonder what this tool does since it comes installed at this path by default on CentOS7

**Comment by jeremyeder** [comment]
I'm not working on this.  Closing.

**Comment by antoinetran** [comment]
Hi @jeremyeder ,

What made you change your mind? I still believe it would be good to avoid a name collision. Thank you.

**Comment by jeremyeder** [comment]
We're not using packer for anything anymore where the benefits of getting it into Fedora would have been helpful.

**Comment by antoinetran** [comment]
@jeremyeder Are you saying that noone use packer from cracklib anymore? If yes, it would be helpful to remove /usr/sbin/packer by RPM update of cracklib, don't you agree?

**Comment by rehman000** [comment]
# Why is this still an issue in 2025?

There are two potential ways to get around this issue without touching essential system binaries in **RHEL/Fedora** based systems:

#### **Option 1:** Create an alias called `pkr` that points to the `/usr/bin/packer` binary:

```bash
echo "alias pkr='/usr/bin/packer'" >> ~/.bashrc
source ~/.bashrc
pkr --version
```

**Pros:** The HashiCorp `packer` binary stays in the default location `/usr/bin/packer` so any upgrades via `dnf` won't be impacted. 
**Cons:** Aliases are typically not a good solution. 


#### **Option 2:** Move `/usr/bin/packer` binary to `/root/bin`:

If you observe the default `$PATH` you'll realize the problem the binaries in `/usr/sbin/packer` take priority over the binaries in `/usr/bin/packer`, so we can get around this by moving the `packer` binary to another directory that takes precedence over `/usr/sbin`: 

```bash
echo $PATH
/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
mkdir /root/bin
cp -p /usr/bin/packer  /root/bin
packer --version
```

**Pros:**  You don't have to re-name the binary using aliases.
**Cons:** Any upgrades via `dnf` to the packer binary will need to be copied over and overwrite the older binary in `/root/bin`.

**Comment by jandd** [comment]
it does not make sense to complain here about decisions made by RedHat packagers. Building cracklib from source does not produce a `packer` binary or symbolic link. The binary produced by make is called `cracklib-packer` and is installed into the prefix given to `configure`.

If any RedHat user has filed an issue in a public RedHat bug tracker it may be a good idea to link it here as a reference for other people finding this issue.
