### ISSUE TITLE
packlib.c: byte order should not be host-specific, and be the same everywhere

### ISSUE THREAD

**Issue by kanavin** [cracklib/cracklib#74]
As highlighted here:
https://github.com/cracklib/cracklib/pull/41

(there's a proposed patch that needs further work, or a full rewrite)

**Comment by beroset** [comment]
I'm starting to write a new patch to address this, and I have some questions:

1. Based on the comments on the previously proposed patch, my inclination is to use *little endian* as the storage order.   Any objections?
2. the `src/lib/packlib.c` file currently has a mix of spaces and tabs.  Do we have a preference?
3. I'm inclined to write some checks in `configure.ac` that would check for the existence of `<endian.h>` or `<sys/endian.h>` and generated an appropriate local header.  This is the approach used in the alsa project.  Any objections or suggestions for a better approach?
4. for conversion of existing dictionaries, should we *read* either form but only *write* little endian?

**Comment by beroset** [comment]
The merged patch always saves the dictionary as little-endian but accepts either little- or big-endian dictionaries to read.  I think we can now close this.

**Comment by nneul** [comment]
Note - I did bump planned version to 2.10 since this can introduce an incompatibility if a newly generated dict is used with an app linked against old library.
