### ISSUE TITLE
Remove autogen.sh

### ISSUE THREAD

**Issue by rossburton** [cracklib/cracklib#76]
The `autogen.sh` does this:

```
autopoint -f
cd m4
echo EXTRA_DIST = *.m4 > Makefile.am
cd ..
autoreconf -f -i
```

`autoreconf` will call `autopoint` if it detects that gettext is being used. `autoconf` will automatically dist any m4 files that are used.

So these changes make the `autogen.sh` redundant:

```
diff --git a/src/Makefile.am b/src/Makefile.am
index 05340bb..b9f8544 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -1 +1 @@
-SUBDIRS = m4 lib util po doc python dicts
+SUBDIRS = lib util po doc python dicts
diff --git a/src/configure.ac b/src/configure.ac
index e25f63e..d822902 100644
--- a/src/configure.ac
+++ b/src/configure.ac
@@ -102 +102 @@ AC_CONFIG_FILES([util/Makefile lib/Makefile doc/Makefile python/Makefile Makefil
-               po/Makefile.in m4/Makefile dicts/Makefile cracklib.spec])
+               po/Makefile.in dicts/Makefile cracklib.spec])
```

I've demonstrated this by starting with a clean git checkout, making the changes above, and running `autoreconf -sif && ./configure && make && make distcheck` (where distcheck will build a tarball and then verify that will build successfully).

**Comment by vapier** [comment]
I disagree we should remove autogen.sh, even if we can simplify it to a single command. autotools is not overtly obvious, so having the shell script makes it easier for new people to contribute, and really doesn't cost us anything.

I think you're right we can simplify the autopoint logic by deleting it and moving the creation to after we run autoreconf.

but I disagree we should drop the m4 files from the distribution. it makes it easier for people to patch and make changes from a release tarball, and it doesn't really cost us anything to keep it. regenerating autotools in a release it obviously not expected or required, but it is nice to do it in a pinch.

**Comment by rossburton** [comment]
> I disagree we should remove autogen.sh, even if we can simplify it to a single command. autotools is not overtly obvious, so having the shell script makes it easier for new people to contribute, and really doesn't cost us anything.

I think this can be mitigated by writing “run autoreconf” in the docs for how to build from git,  it that’s fine. 

> but I disagree we should drop the m4 files from the distribution. it makes it easier for people to patch and make changes from a release tarball, and it doesn't really cost us anything to keep it. regenerating autotools in a release it obviously not expected or required, but it is nice to do it in a pinch.

I must not have been clear enough. Autoconf knows that it installed m4 files and puts them in the tarball automatically. No other project that uses autoconf has to manually list the m4 files in EXTRA_DIST.

**Comment by vapier** [comment]
if the m4 files get auto bundled by `make dist`, then agreed we can drop the logic.

keeping a single line script that just runs `exec autoreconf -vfi` costs nothing and helps devs & newbies. I'm ambivalent on what the docs recommend.

**Comment by nneul** [comment]
I'm in agreement on addressing the 'm4 files in extra_dist' - if you can confirm that works properly, please send a PR with the changes.

I'm very much in the 'keep autogen.sh' camp as that is a general consistent expectation across MANY projects, even if it is just a trivial wrapper.
