### ISSUE TITLE
cracklib-check: improve output when checking passwords

### ISSUE THREAD

**Issue by yixiangzhike** [cracklib/cracklib#77]
I check my password before setting using by cracklib-check, but it echoes the plaintext password to the terminal.
This may allow others to obtain the password. I think we should avoid displaying plaintext password on the terminal.

For example: 
[root@localhost ~]# cracklib-check 
TestPwd12    
TestPwd12: it is based on a dictionary word
T1e9s$Pwd    
T1e9s$Pwd: OK

I have a change like this,  please review.
```
diff --git a/util/check.c b/util/check.c
--- a/util/check.c
+++ b/util/check.c
@@ -8,6 +8,8 @@
 #include <limits.h>
 #include <string.h>
 #include <locale.h>
+#include <termios.h>
+#include <unistd.h>
 
 #define IN_CRACKLIB
 #include "config.h"
@@ -20,6 +22,8 @@ main(int argc, char **argv)
 	char buf[LINE_MAX];
 	const char *why;
 	int i;
+	int result = -1;
+	struct termios tios;
 
 	setlocale(LC_ALL, "");
 
@@ -27,6 +31,11 @@ main(int argc, char **argv)
 	bindtextdomain(PACKAGE, LOCALEDIR);
 	textdomain(PACKAGE);
 #endif
+	result = tcgetattr(STDIN_FILENO, &tios);
+	if (!result) {
+	    tios.c_lflag &= ~ECHO;
+	    tcsetattr(STDIN_FILENO, TCSAFLUSH, &tios);
+	}
 
 	while (fgets(buf, sizeof(buf), stdin) != NULL) {
 		while (((i = strlen(buf)) > 0) && (i > 0)) {
@@ -44,7 +53,7 @@ main(int argc, char **argv)
 		if ((why != NULL) && (strlen(why) > 0)) {
 			printf("%s: %s\n", buf, why);
 		} else {
-			printf("%s: OK\n", buf);
+			printf("It is OK\n");
 		}
 	}
 	return 0;
```

**Comment by tomato42** [comment]
the reason for that, is so that it's possible to check multiple passwords with one command invocation; a command line option to stop echoing would probably be a better idea...

**Comment by yixiangzhike** [comment]
> the reason for that, is so that it's possible to check multiple passwords with one command invocation; a command line option to stop echoing would probably be a better idea...

Users know the full list of passwords, outputting only the unavailable passwords should be enough when checking for multiple passwords.

**Comment by vapier** [comment]
disagree it's a security issue, but agree it could be improved without impacting usability

@tomato42's suggestion sounds reasonable

please send a PR rather than post diffs inline in issues
