### ISSUE TITLE
various warnings from the compiler

### ISSUE THREAD

**Issue by hdatma** [cracklib/cracklib#8]
[compiler-stderr.log.txt](https://github.com/cracklib/cracklib/files/465379/compiler-stderr.log.txt)

**Comment by vladak** [comment]
It would be better if such issues were accompanied by a PR. Anyhow, I went through the warnings in the attached file and:
  - `vers_id` is no longer present anywhere in the code
  - `Debug()` was just change to variadic function in 97b0f7291f36e1679fe01e9e3c2896c12291eccb so the warnings about argument count/type no longer apply I believe
  - the check was done with clang 3.9. I did `CC=clang ./configure && make clean && make` with Clang 14.0.0-1ubuntu1.1 and did not get any warnings

There are no other warnings in the log.

Considering the above, I think this issue can be closed.
