### ISSUE TITLE
2.10.0 compile error on Arch Linux  (make check doesn't work with 'make -j 4')

### ISSUE THREAD

**Issue by tpowa** [cracklib/cracklib#93]
Hi,
I get this compile error while trying to build for Arch Linux:
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/cracklib/src=/usr/src/debug/cracklib -flto=auto  -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now          -Wl,-z,pack-relative-relocs -flto=auto -o testlib testlib.o ../lib/libcrack.la -lz 
../lib/packlib.c:21:9: warning: "_DEFAULT_SOURCE" redefined
   21 | #define _DEFAULT_SOURCE
      |         ^~~~~~~~~~~~~~~
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/string.h:26,
                 from ../lib/packlib.c:8:
/usr/include/features.h:246:10: note: this is the location of the previous definition
  246 | # define _DEFAULT_SOURCE        1
Staying on 2.9.11  on Arch Linux until this is fixed.
Cheers
tpowa

**Comment by nneul** [comment]
Can you try adding an `#undef DEFAULT_SOURCE` before the `#define DEFAULT_SOURCE` in lib/packlib.c and see if it builds ok for you?

**Comment by nneul** [comment]
Please note though - that's a warning, not an error. Are you actually having an _error_ doing the compilation?

**Comment by tpowa** [comment]
Ah good hint, setting !makeflags makes it compile in my PKGBUILD.

**Comment by tpowa** [comment]
My MAKEFLAGS are normally -j4 on this machine, this worked in 2.9.11. Is there a way to get it compiled with this makeflags or is building without makeflags the better default?

**Comment by tpowa** [comment]
make[2]: *** [Makefile:1279: baddict] Error 127
make[2]: *** Waiting for unfinished jobs....
51526 51526
mv -f .deps/make_bad_endian-packlib.Tpo .deps/make_bad_endian-packlib.Po
libtool: link: gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/cracklib/src=/usr/src/debug/cracklib -flto=auto -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z -Wl,pack-relative-relocs -flto=auto -o .libs/testlib testlib.o  ../lib/.libs/libcrack.so -lz

**Comment by nneul** [comment]
Ah, that looks completely unrelated to above warning. May be a dependency order issue for the util subdir that is coming up with the parallel make.

**Comment by nneul** [comment]
What's your top level make command?

Are you running something like `make -j 4 all check` ?

**Comment by tpowa** [comment]
Yes, now I see my log shows it fails in check part.
[cracklib-2.10.0-1-x86_64-check.log](https://github.com/user-attachments/files/16353482/cracklib-2.10.0-1-x86_64-check.log)

**Comment by nneul** [comment]
Looks like it's just check that doesn't like the parallel run.

**Comment by nneul** [comment]
Try latest main and see if it works clean for you with -j4. Fixed missing dependency that was causing make check to not parallelize.

**Comment by tpowa** [comment]
Confirmed, latest git does not show warning and fixed the parallel check run. Thank you very much :)

**Comment by nneul** [comment]
You need a new release (i.e. is this blocking rolling into a distro update or similar)?

**Comment by tpowa** [comment]
No, I fixed the our main package now with make -j 1 check. If you like to release a new tag I go straight for this.

**Comment by nneul** [comment]
I'll try to get a release rolled out sometime soon, can't do right at the moment though.

**Comment by tpowa** [comment]
Perfect, looking forward then :), 2.10.0 will sit in our testing repository. I can wait until 2.10.1 to move to our core repository.

**Comment by nneul** [comment]
2.10.1 was released.
